image: node:18.17.1-alpine

stages:
    - build
    - deploy

build-image:
    stage: build
    image: docker:git
    services:
        - docker:23-dind
    variables:
        DOCKER_DRIVER: overlay
        DOCKER_HOST: tcp://docker:2375
        IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
        IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - docker build --tag=$IMAGE_TAG . --pull -t $IMAGE_NAME
        - docker push $IMAGE_NAME
    only:
        - valid
        - master
    when: manual
