@token = dda6d0c1-88d6-4bd9-9c50-2121bb256108

POST http://localhost:3000/chargepoly/users HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

{
    "email": "damien@chargepoly.com",
    "password": "$2b$10$e01VASi7lfyBimwsbuvc9edo4Au90Emd1fLHMinW5hGzGfENzf6qm"
}